name: all_widget2
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  flutter_inset_box_shadow: ^1.0.8
  flutter_spinkit: ^5.1.0
  argon_buttons_flutter_fix: ^1.1.3
  pdf: ^3.8.4
  # save file
  path_provider: ^2.0.1
  # open pdf document
  open_file: ^3.1.0
  easy_stepper: ^0.1.4+1
  analog_clock: ^0.1.1
  syncfusion_flutter_gauges: ^20.3.60
  badges: ^2.0.3
  voice_message_package: ^0.0.74
  syncfusion_flutter_sliders: ^20.3.60
  syncfusion_flutter_charts: ^20.3.47
  slider_side_menu: ^0.1.0
  side_menu_animation:
  sizer:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/image/fruit.svg


  fonts:
     - family: IconFont
       fonts:
         - asset: assets/fonts/IconFont.ttf
