name: all_widget2
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  flutter_inset_box_shadow: ^1.0.8
  flutter_spinkit: ^5.1.0
  argon_buttons_flutter_fix: ^1.1.3
  pdf: ^3.8.4
  # save file
  path_provider: ^2.0.1
  # open pdf document
  open_file: ^3.1.0
  easy_stepper:
  analog_clock: ^0.1.1
  syncfusion_flutter_gauges: ^20.3.60
  badges: ^2.0.3
  voice_message_package: ^0.0.74
  syncfusion_flutter_sliders: ^20.3.60
  syncfusion_flutter_charts: ^20.3.47
  slider_side_menu: ^0.1.0
  jtdetector: ^1.3.1
  ticket_material: ^0.3.1
  ticket_widget: ^0.0.1
  carousel_indicator: ^1.0.6
  flutter_animated_icons: ^1.0.1
  shimmer: ^2.0.0
  flutter_typeahead: ^4.3.7
  circular_reveal_animation: ^2.0.1
  add_to_cart_animation: ^2.0.3
  flutter_staggered_animations: ^1.1.1
  clickable_list_wheel_view: ^0.2.0
  shaky_animated_listview: ^0.0.5
  transformable_list_view: ^0.2.0
  animation_list: ^2.2.1
  auto_animated: ^3.1.0
  loading_animation_widget: ^1.2.0+4
  animations: ^2.0.7
  searchbar_animation: ^0.0.4
  searchable_listview: ^2.2.2
  liquid_pull_to_refresh: ^3.0.1
  dots_indicator: ^2.1.0
  flutter_rating_bar: ^4.0.1
  rating_dialog: ^2.0.4
  custom_rating_bar: ^2.0.4
  smooth_star_rating_null_safety: ^1.0.4+2
  rating_summary: ^1.0.1+1
  in_app_review: ^2.0.6
  loadmore_listview: ^1.0.6
  flutter_reorderable_grid_view: ^4.0.0
  smooth_sort: ^2.0.1
  bottom_bar_with_sheet: ^2.4.0
  icons_plus: ^4.0.0
  photo_card_swiper: ^0.0.6
  proste_bezier_curve: ^2.0.2
  glassmorphism: ^3.0.0
  youtube_player_iframe: ^4.0.4
  adaptive_action_sheet: ^2.0.2
  app_settings: ^4.2.0
  flutter_credit_card: ^3.0.6
  html:
  side_menu_animation:
  sizer:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/image/fruit.svg


  fonts:
     - family: IconFont
       fonts:
         - asset: assets/fonts/IconFont.ttf
